# Generated by Django 5.1.2 on 2024-11-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('customer', models.CharField(max_length=100)),
                ('created', models.BigIntegerField()),
                ('created_hr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLabelPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('label_operations', models.JSONField()),
                ('label_positions', models.JSONField()),
                ('comment', models.TextField()),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('timestamp_hr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('operation_ids', models.JSONField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('label_operations', models.JSONField()),
                ('label_positions', models.JSONField()),
                ('comment', models.TextField()),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('timestamp_hr', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='backend.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField()),
                ('operation_id', models.IntegerField()),
                ('description', models.TextField()),
                ('cost_group', models.CharField(max_length=100)),
                ('machine_group', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='backend.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOperationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('operation', models.CharField(max_length=100)),
                ('operation_description', models.TextField()),
                ('cost_group', models.CharField(max_length=100)),
                ('machine_group', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('stop', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_executions', to='backend.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='backend.order')),
            ],
        ),
        migrations.CreateModel(
            name='ActionUpdateLabelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('custom_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.updatelabel')),
            ],
        ),
        migrations.CreateModel(
            name='ActionUpdateLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('custom_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.updatelabel')),
            ],
        ),
    ]
